ARG GIT_TAG=${GIT_TAG:-main}

FROM node:lts-alpine3.18

ARG GIT_TAG

ENV HOME=/app

WORKDIR /app

RUN apk add --no-cache git && \
    npm install -g pnpm && \
    git clone --force -b ${GIT_TAG} --depth 1 https://github.com/zyachel/quetre.git . && \
    cp .env.example .env && \
    pnpm install --prod && \
    chown -R 1000:1000 /app

USER 1000

EXPOSE 3000

CMD ["pnpm", "start"]