services:

  quetre:
    container_name: quetre
    image: ceramicwhite/quetre:dev
    init: true
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"